// Code generated by mockery v2.33.0. DO NOT EDIT.

package mocks

import (
	context "context"

	log "github.com/pollykon/avito_test_task/internal/service/log"

	mock "github.com/stretchr/testify/mock"
)

// LogService is an autogenerated mock type for the LogService type
type LogService struct {
	mock.Mock
}

type LogService_Expecter struct {
	mock *mock.Mock
}

func (_m *LogService) EXPECT() *LogService_Expecter {
	return &LogService_Expecter{mock: &_m.Mock}
}

// GenerateCSV provides a mock function with given fields: ctx, request
func (_m *LogService) GenerateCSV(ctx context.Context, request log.GetCSVRequest) (string, error) {
	ret := _m.Called(ctx, request)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, log.GetCSVRequest) (string, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, log.GetCSVRequest) string); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, log.GetCSVRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LogService_GenerateCSV_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateCSV'
type LogService_GenerateCSV_Call struct {
	*mock.Call
}

// GenerateCSV is a helper method to define mock.On call
//   - ctx context.Context
//   - request log.GetCSVRequest
func (_e *LogService_Expecter) GenerateCSV(ctx interface{}, request interface{}) *LogService_GenerateCSV_Call {
	return &LogService_GenerateCSV_Call{Call: _e.mock.On("GenerateCSV", ctx, request)}
}

func (_c *LogService_GenerateCSV_Call) Run(run func(ctx context.Context, request log.GetCSVRequest)) *LogService_GenerateCSV_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(log.GetCSVRequest))
	})
	return _c
}

func (_c *LogService_GenerateCSV_Call) Return(_a0 string, _a1 error) *LogService_GenerateCSV_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *LogService_GenerateCSV_Call) RunAndReturn(run func(context.Context, log.GetCSVRequest) (string, error)) *LogService_GenerateCSV_Call {
	_c.Call.Return(run)
	return _c
}

// NewLogService creates a new instance of LogService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLogService(t interface {
	mock.TestingT
	Cleanup(func())
}) *LogService {
	mock := &LogService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
