version: "3"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_HOST: ${PG_HOST}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE_NAME}
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - database-volume:/var/lib/postgresql/data
volumes:
  database-volume: