// Code generated by mockery v2.33.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Transaction is an autogenerated mock type for the Transaction type
type Transaction struct {
	mock.Mock
}

type Transaction_Expecter struct {
	mock *mock.Mock
}

func (_m *Transaction) EXPECT() *Transaction_Expecter {
	return &Transaction_Expecter{mock: &_m.Mock}
}

// TransactionWrapper provides a mock function with given fields: ctx, f
func (_m *Transaction) TransactionWrapper(ctx context.Context, f func(context.Context) error) error {
	ret := _m.Called(ctx, f)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(context.Context) error) error); ok {
		r0 = rf(ctx, f)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Transaction_TransactionWrapper_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TransactionWrapper'
type Transaction_TransactionWrapper_Call struct {
	*mock.Call
}

// TransactionWrapper is a helper method to define mock.On call
//   - ctx context.Context
//   - f func(context.Context) error
func (_e *Transaction_Expecter) TransactionWrapper(ctx interface{}, f interface{}) *Transaction_TransactionWrapper_Call {
	return &Transaction_TransactionWrapper_Call{Call: _e.mock.On("TransactionWrapper", ctx, f)}
}

func (_c *Transaction_TransactionWrapper_Call) Run(run func(ctx context.Context, f func(context.Context) error)) *Transaction_TransactionWrapper_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(func(context.Context) error))
	})
	return _c
}

func (_c *Transaction_TransactionWrapper_Call) Return(_a0 error) *Transaction_TransactionWrapper_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Transaction_TransactionWrapper_Call) RunAndReturn(run func(context.Context, func(context.Context) error) error) *Transaction_TransactionWrapper_Call {
	_c.Call.Return(run)
	return _c
}

// NewTransaction creates a new instance of Transaction. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransaction(t interface {
	mock.TestingT
	Cleanup(func())
}) *Transaction {
	mock := &Transaction{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
