// Code generated by mockery v2.33.0. DO NOT EDIT.

package mocks

import (
	context "context"
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// SegmentService is an autogenerated mock type for the SegmentService type
type SegmentService struct {
	mock.Mock
}

type SegmentService_Expecter struct {
	mock *mock.Mock
}

func (_m *SegmentService) EXPECT() *SegmentService_Expecter {
	return &SegmentService_Expecter{mock: &_m.Mock}
}

// AddUserToSegment provides a mock function with given fields: ctx, userID, slugs, ttl
func (_m *SegmentService) AddUserToSegment(ctx context.Context, userID int64, slugs []string, ttl *time.Duration) error {
	ret := _m.Called(ctx, userID, slugs, ttl)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, []string, *time.Duration) error); ok {
		r0 = rf(ctx, userID, slugs, ttl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SegmentService_AddUserToSegment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddUserToSegment'
type SegmentService_AddUserToSegment_Call struct {
	*mock.Call
}

// AddUserToSegment is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - slugs []string
//   - ttl *time.Duration
func (_e *SegmentService_Expecter) AddUserToSegment(ctx interface{}, userID interface{}, slugs interface{}, ttl interface{}) *SegmentService_AddUserToSegment_Call {
	return &SegmentService_AddUserToSegment_Call{Call: _e.mock.On("AddUserToSegment", ctx, userID, slugs, ttl)}
}

func (_c *SegmentService_AddUserToSegment_Call) Run(run func(ctx context.Context, userID int64, slugs []string, ttl *time.Duration)) *SegmentService_AddUserToSegment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].([]string), args[3].(*time.Duration))
	})
	return _c
}

func (_c *SegmentService_AddUserToSegment_Call) Return(_a0 error) *SegmentService_AddUserToSegment_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SegmentService_AddUserToSegment_Call) RunAndReturn(run func(context.Context, int64, []string, *time.Duration) error) *SegmentService_AddUserToSegment_Call {
	_c.Call.Return(run)
	return _c
}

// NewSegmentService creates a new instance of SegmentService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSegmentService(t interface {
	mock.TestingT
	Cleanup(func())
}) *SegmentService {
	mock := &SegmentService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
