// Code generated by mockery v2.33.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// CSVRepository is an autogenerated mock type for the CSVRepository type
type CSVRepository struct {
	mock.Mock
}

type CSVRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *CSVRepository) EXPECT() *CSVRepository_Expecter {
	return &CSVRepository_Expecter{mock: &_m.Mock}
}

// Save provides a mock function with given fields: csv
func (_m *CSVRepository) Save(csv string) (string, error) {
	ret := _m.Called(csv)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(csv)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(csv)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(csv)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CSVRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type CSVRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - csv string
func (_e *CSVRepository_Expecter) Save(csv interface{}) *CSVRepository_Save_Call {
	return &CSVRepository_Save_Call{Call: _e.mock.On("Save", csv)}
}

func (_c *CSVRepository_Save_Call) Run(run func(csv string)) *CSVRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *CSVRepository_Save_Call) Return(_a0 string, _a1 error) *CSVRepository_Save_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CSVRepository_Save_Call) RunAndReturn(run func(string) (string, error)) *CSVRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewCSVRepository creates a new instance of CSVRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCSVRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CSVRepository {
	mock := &CSVRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
