// Code generated by mockery v2.33.0. DO NOT EDIT.

package mocks

import (
	context "context"

	log "github.com/pollykon/avito_test_task/internal/repository/log"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// LogRepository is an autogenerated mock type for the LogRepository type
type LogRepository struct {
	mock.Mock
}

type LogRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *LogRepository) EXPECT() *LogRepository_Expecter {
	return &LogRepository_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, userID, from, to
func (_m *LogRepository) Get(ctx context.Context, userID int64, from time.Time, to time.Time) ([]log.Log, error) {
	ret := _m.Called(ctx, userID, from, to)

	var r0 []log.Log
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, time.Time, time.Time) ([]log.Log, error)); ok {
		return rf(ctx, userID, from, to)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, time.Time, time.Time) []log.Log); ok {
		r0 = rf(ctx, userID, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]log.Log)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, time.Time, time.Time) error); ok {
		r1 = rf(ctx, userID, from, to)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LogRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type LogRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - from time.Time
//   - to time.Time
func (_e *LogRepository_Expecter) Get(ctx interface{}, userID interface{}, from interface{}, to interface{}) *LogRepository_Get_Call {
	return &LogRepository_Get_Call{Call: _e.mock.On("Get", ctx, userID, from, to)}
}

func (_c *LogRepository_Get_Call) Run(run func(ctx context.Context, userID int64, from time.Time, to time.Time)) *LogRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(time.Time), args[3].(time.Time))
	})
	return _c
}

func (_c *LogRepository_Get_Call) Return(_a0 []log.Log, _a1 error) *LogRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *LogRepository_Get_Call) RunAndReturn(run func(context.Context, int64, time.Time, time.Time) ([]log.Log, error)) *LogRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// NewLogRepository creates a new instance of LogRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLogRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *LogRepository {
	mock := &LogRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
